name: Integration Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:4.2.17
        options: >-
          --health-cmd "echo 'db.runCommand(\"ping\").ok' | mongo --host localhost --quiet --eval 'db.version()'
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore src/Horarium.sln

      - name: Build project
        run: dotnet build src/Horarium.sln --configuration Release --no-restore

      - name: Run MongoDB integration tests
        run: DataBase=MongoDB dotnet test src/Horarium.IntegrationTest/Horarium.IntegrationTest.csproj -c Release --no-build --no-restore
        env:
          MONGO_ADDRESS: mongodb://localhost:27017

      - name: Run InMemory integration tests
        run: DataBase=Memory dotnet test src/Horarium.IntegrationTest/Horarium.IntegrationTest.csproj -c Release --no-build --no-restore

