name: Integration Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false 
      matrix:
        test_type: [ 'MongoDB', 'Memory' ]

    services:
      mongodb:
        if: ${{ matrix.test_type == 'MongoDB' }}
        image: mongo:4.2.17
        options: >-
          --health-cmd "echo 'db.runCommand(\"ping\").ok' | mongo --host localhost --quiet --eval 'db.version()'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore src/Horarium.sln

      - name: Build project
        run: dotnet build src/Horarium.sln --configuration Release --no-restore

      # 将两个测试步骤合并为一个，并根据矩阵变量设置环境
      - name: Run ${{ matrix.test_type }} integration tests
        run: dotnet test src/Horarium.IntegrationTest/Horarium.IntegrationTest.csproj -c Release --no-build --no-restore
        env:
          # 只为 MongoDB 作业设置 MONGO_ADDRESS
          MONGO_ADDRESS: ${{ matrix.test_type == 'MongoDB' && 'localhost' || '' }}
          # 根据矩阵变量设置 DataBase
          DataBase: ${{ matrix.test_type }}
