name: Unit Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore src/Horarium.sln

      - name: Build project
        run: dotnet build src/Horarium.sln --configuration Release --no-restore

      - name: Run unit tests
        run: dotnet test src/Horarium.Test/Horarium.Test.csproj --configuration Release --no-build --no-restore
